# Generated by Django 5.2.4 on 2026-07-05 08:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Question Text')),
                ('question_type', models.CharField(choices=[('single_choice', 'Single Choice'), ('multiple_choice', 'Multiple Choice'), ('true_false', 'True/False')], default='single_choice', max_length=20, verbose_name='Question Type')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('points', models.PositiveIntegerField(default=1, verbose_name='Points')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'db_table': 'questions',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Option Text')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Is Correct')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='assessments.question', verbose_name='Question')),
            ],
            options={
                'verbose_name': 'Option',
                'verbose_name_plural': 'Options',
                'db_table': 'options',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('time_limit_minutes', models.PositiveIntegerField(default=0, help_text='0 means no time limit', verbose_name='Time Limit (minutes)')),
                ('passing_score', models.DecimalField(decimal_places=2, default=50.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Passing Score (%)')),
                ('max_attempts', models.PositiveIntegerField(default=0, help_text='0 means unlimited attempts', verbose_name='Max Attempts')),
                ('is_published', models.BooleanField(default=False, verbose_name='Is Published')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='courses.course', verbose_name='Course')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizzes',
                'db_table': 'quizzes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessments.quiz', verbose_name='Quiz'),
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('submitted', 'Submitted')], default='in_progress', max_length=20, verbose_name='Status')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Score (%)')),
                ('is_passed', models.BooleanField(default=False, verbose_name='Is Passed')),
                ('total_questions', models.PositiveIntegerField(default=0, verbose_name='Total Questions')),
                ('correct_answers', models.PositiveIntegerField(default=0, verbose_name='Correct Answers')),
                ('time_taken_seconds', models.PositiveIntegerField(default=0, verbose_name='Time Taken (seconds)')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Started At')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Submitted At')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL, verbose_name='Student')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='assessments.quiz', verbose_name='Quiz')),
            ],
            options={
                'verbose_name': 'Attempt',
                'verbose_name_plural': 'Attempts',
                'db_table': 'attempts',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Is Correct')),
                ('points_earned', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Points Earned')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='assessments.attempt', verbose_name='Attempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='assessments.question', verbose_name='Question')),
                ('selected_options', models.ManyToManyField(blank=True, to='assessments.option', verbose_name='Selected Options')),
            ],
            options={
                'verbose_name': 'Result',
                'verbose_name_plural': 'Results',
                'db_table': 'results',
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
