# Generated by Django 6.0.6 on 2026-07-05 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('login', 'Login'), ('register', 'Register'), ('enrollment', 'Course Enrollment'), ('lesson_completed', 'Lesson Completed'), ('course_completed', 'Course Completed'), ('quiz_started', 'Quiz Started'), ('quiz_submitted', 'Quiz Submitted'), ('assignment_submitted', 'Assignment Submitted'), ('assignment_graded', 'Assignment Graded'), ('certificate_issued', 'Certificate Issued'), ('payment', 'Payment Made'), ('review', 'Review Submitted')], max_length=30, verbose_name='Action Type')),
                ('description', models.CharField(max_length=500, verbose_name='Description')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional context as JSON (e.g. course_id, quiz_id, etc.)', verbose_name='Metadata')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'db_table': 'activity_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='activity_lo_user_id_b8c999_idx'), models.Index(fields=['action_type'], name='activity_lo_action__9e4610_idx'), models.Index(fields=['created_at'], name='activity_lo_created_166e11_idx')],
            },
        ),
    ]
