# Generated by Django 6.0.6 on 2026-07-20 18:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentfee',
            name='fee_type',
        ),
        migrations.AddField(
            model_name='studentfee',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_fees', to='courses.course', verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='total_fee',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Course Fee'),
        ),
    ]
