# Generated by Django 6.0.6 on 2026-07-20 18:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_remove_studentfee_fee_type_studentfee_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructorsalary',
            name='base_salary',
        ),
        migrations.AddField(
            model_name='instructorsalary',
            name='commission_percentage',
            field=models.DecimalField(decimal_places=2, default=70.0, help_text='Percentage of course revenue paid to instructor', max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Commission (%)'),
        ),
        migrations.AddField(
            model_name='instructorsalary',
            name='total_revenue',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Total fees collected from students for this instructor's courses", max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total Course Revenue'),
        ),
    ]
