# Generated by Django 6.0.6 on 2026-07-05 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Title')),
                ('content', models.TextField(blank=True, verbose_name='Content')),
                ('link_url', models.URLField(blank=True, verbose_name='Link URL')),
                ('link_text', models.CharField(blank=True, max_length=100, verbose_name='Link Text')),
                ('announcement_type', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('success', 'Success'), ('promotion', 'Promotion')], default='info', max_length=20, verbose_name='Type')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_dismissible', models.BooleanField(default=True, verbose_name='Is Dismissible')),
                ('starts_at', models.DateTimeField(verbose_name='Starts At')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expires At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'db_table': 'announcements',
                'ordering': ['-starts_at'],
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('subtitle', models.CharField(blank=True, max_length=400, verbose_name='Subtitle')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='Banner Image')),
                ('mobile_image', models.ImageField(blank=True, help_text='Optional: optimized image for mobile devices', null=True, upload_to='banners/', verbose_name='Mobile Image')),
                ('link_url', models.URLField(blank=True, verbose_name='Link URL')),
                ('link_text', models.CharField(blank=True, max_length=100, verbose_name='Link Text')),
                ('button_style', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('outline', 'Outline')], default='primary', max_length=20, verbose_name='Button Style')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'db_table': 'banners',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FAQCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'FAQ Category',
                'verbose_name_plural': 'FAQ Categories',
                'db_table': 'faq_categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='LMS', max_length=200, verbose_name='Site Name')),
                ('site_tagline', models.CharField(blank=True, max_length=300, verbose_name='Tagline')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Logo')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Favicon')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email Address')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook URL')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter/X URL')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn URL')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube URL')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram URL')),
                ('default_meta_title', models.CharField(blank=True, max_length=70, verbose_name='Default Meta Title')),
                ('default_meta_description', models.CharField(blank=True, max_length=160, verbose_name='Default Meta Description')),
                ('google_analytics_id', models.CharField(blank=True, max_length=50, verbose_name='Google Analytics ID')),
                ('cache_ttl_seconds', models.PositiveIntegerField(default=300, help_text='How long to cache public CMS pages (default: 5 minutes)', verbose_name='Cache TTL (seconds)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
                'db_table': 'site_settings',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, verbose_name='Question')),
                ('answer', models.TextField(verbose_name='Answer')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faqs', to='cms.faqcategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'db_table': 'faqs',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, help_text='SEO title (recommended: 50-60 characters)', max_length=70, verbose_name='Meta Title')),
                ('meta_description', models.CharField(blank=True, help_text='SEO description (recommended: 150-160 characters)', max_length=160, verbose_name='Meta Description')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, verbose_name='Meta Keywords')),
                ('og_image', models.ImageField(blank=True, help_text='Open Graph image for social sharing', null=True, upload_to='seo/', verbose_name='OG Image')),
                ('title', models.CharField(max_length=300, verbose_name='Title')),
                ('slug', models.SlugField(max_length=300, unique=True, verbose_name='Slug')),
                ('content', models.TextField(help_text='Page content (HTML supported)', verbose_name='Content')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='pages/', verbose_name='Featured Image')),
                ('is_published', models.BooleanField(default=False, verbose_name='Is Published')),
                ('show_in_footer', models.BooleanField(default=False, help_text='Show a link in the site footer', verbose_name='Show in Footer')),
                ('footer_order', models.PositiveIntegerField(default=0, verbose_name='Footer Order')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='View Count')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Published At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
                'db_table': 'pages',
                'ordering': ['title'],
                'indexes': [models.Index(fields=['slug'], name='pages_slug_2ebe9d_idx'), models.Index(fields=['is_published'], name='pages_is_publ_b61b27_idx')],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, help_text='SEO title (recommended: 50-60 characters)', max_length=70, verbose_name='Meta Title')),
                ('meta_description', models.CharField(blank=True, help_text='SEO description (recommended: 150-160 characters)', max_length=160, verbose_name='Meta Description')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, verbose_name='Meta Keywords')),
                ('og_image', models.ImageField(blank=True, help_text='Open Graph image for social sharing', null=True, upload_to='seo/', verbose_name='OG Image')),
                ('title', models.CharField(max_length=300, verbose_name='Title')),
                ('slug', models.SlugField(max_length=300, unique=True, verbose_name='Slug')),
                ('excerpt', models.TextField(blank=True, help_text='Short summary shown in blog listings', max_length=500, verbose_name='Excerpt')),
                ('content', models.TextField(verbose_name='Content')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='Featured Image')),
                ('category', models.CharField(blank=True, help_text='e.g. News, Tutorial, Announcement', max_length=100, verbose_name='Category')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=500, verbose_name='Tags')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20, verbose_name='Status')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured Post')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='View Count')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Published At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'db_table': 'blog_posts',
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['slug'], name='blog_posts_slug_b4ca25_idx'), models.Index(fields=['status', '-published_at'], name='blog_posts_status_d9ff7c_idx'), models.Index(fields=['category'], name='blog_posts_categor_d08396_idx')],
            },
        ),
    ]
