# Generated by Django 5.2.4 on 2026-07-05 09:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('enrollments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Template Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='certificate_templates/', verbose_name='Background Image')),
                ('layout_config', models.JSONField(blank=True, default=dict, help_text='JSON config for text positioning, fonts, colors, etc.', verbose_name='Layout Configuration')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Certificate Template',
                'verbose_name_plural': 'Certificate Templates',
                'db_table': 'certificate_templates',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Certificate ID')),
                ('verification_code', models.CharField(editable=False, max_length=64, unique=True, verbose_name='Verification Code')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='Issued At')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expires At')),
                ('is_revoked', models.BooleanField(default=False, verbose_name='Is Revoked')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='certificates/', verbose_name='PDF File')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='courses.course', verbose_name='Course')),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='enrollments.enrollment', verbose_name='Enrollment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL, verbose_name='Student')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='certificates.certificatetemplate', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
                'db_table': 'certificates',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('is_valid', models.BooleanField(default=True, verbose_name='Is Valid')),
                ('verified_at', models.DateTimeField(auto_now_add=True, verbose_name='Verified At')),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='certificates.certificate', verbose_name='Certificate')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificate_verifications', to=settings.AUTH_USER_MODEL, verbose_name='Verified By')),
            ],
            options={
                'verbose_name': 'Certificate Verification',
                'verbose_name_plural': 'Certificate Verifications',
                'db_table': 'certificate_verifications',
                'ordering': ['-verified_at'],
            },
        ),
    ]
