# Generated by Django 6.0.6 on 2026-07-20 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('instructor', 'Instructor'), ('admin', 'Admin'), ('accounts', 'Accounts')], default='student', max_length=20, verbose_name='User Role'),
        ),
    ]
