# Generated by Django 6.0.6 on 2026-07-04 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Title')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_sections', to='courses.course', verbose_name='Course')),
            ],
            options={
                'verbose_name': 'Learning Section',
                'verbose_name_plural': 'Learning Sections',
                'db_table': 'learning_sections',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Title')),
                ('content_type', models.CharField(choices=[('video', 'Video'), ('document', 'Document'), ('text', 'Text'), ('quiz', 'Quiz')], default='text', max_length=20, verbose_name='Content Type')),
                ('video_url', models.URLField(blank=True, verbose_name='Video URL')),
                ('content', models.TextField(blank=True, verbose_name='Content')),
                ('duration_minutes', models.PositiveIntegerField(default=0, verbose_name='Duration (minutes)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('is_free', models.BooleanField(default=False, verbose_name='Is Free Preview')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course', verbose_name='Course')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='learning.section', verbose_name='Section')),
            ],
            options={
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'Lessons',
                'db_table': 'lessons',
                'ordering': ['order'],
            },
        ),
    ]
